
game:
    version: 1.98
    server: en9
    secret: bTsZ5/8lOyt2Nfqb8qhBDIildUIzz842pzNidXIL6/ytDWSRdtWbuC7upEcwCc/k6cuXDOppjOK/gudECEUTYQ==
    timestamp: 1491392992

login:
    user_key: '***'
    sid: '***'
